const History = window.MeteoHistoryConfig; const chartCache = new Map(); const charts = {}; const CACHE_MS = 600000;
const labels = { "hours=24": "Últimas 24 horas", "days=7": "Últimos 7 días", "days=30": "Últimos 30 días" };
function values(data, key) { return data.map(x => x[key]).filter(Number.isFinite); }
function stat(data, key, kind) { const v=values(data,key); return v.length ? (kind==="min"?Math.min(...v):kind==="max"?Math.max(...v):v.reduce((a,b)=>a+b,0)/v.length) : null; }
function destroyCharts(){ Object.values(charts).forEach(c=>c.destroy()); Object.keys(charts).forEach(k=>delete charts[k]); }
function chart(id, data, datasets, type="line"){ const c=document.getElementById(id); charts[id]=new window.Chart(c,{type,data:{labels:data.map(x=>History.formatDate(x.observedAt,true)),datasets},options:{responsive:true,maintainAspectRatio:false,interaction:{mode:"index",intersect:false},plugins:{legend:{display:datasets.length>1},tooltip:{callbacks:{title:x=>History.formatDate(data[x[0].dataIndex].observedAt,true),afterBody:x=>{const d=data[x[0].dataIndex];return d.windDirection?`Dirección: ${d.windDirection}`:"";}}}},scales:{x:{ticks:{maxTicksLimit:6,color:History.COLORS.muted},grid:{display:false}},y:{ticks:{color:History.COLORS.muted},grid:{color:"rgba(97,115,129,.12)"}}}}}); }
function series(label,key,color,fill=false){return {label,data:[],borderColor:color,backgroundColor:fill?"rgba(25,118,185,.12)":color,borderWidth:2,pointRadius:0,tension:.25,fill};}
function render(data){ destroyCharts(); const temp=series("Temperatura °C","temperature",History.COLORS.blue,true), hum=series("Humedad %","humidity",History.COLORS.blue), pre=series("Presión hPa","pressure",History.COLORS.navy), wind=series("Viento km/h","windSpeed",History.COLORS.blue), gust=series("Ráfagas km/h","windGust",History.COLORS.gust), rain={label:"Intensidad mm/h",data:[],backgroundColor:History.COLORS.rain,borderColor:History.COLORS.rain}; [temp,hum,pre,wind,gust,rain].forEach(s=>{const key=s.label.startsWith("Temperatura")?"temperature":s.label.startsWith("Humedad")?"humidity":s.label.startsWith("Presión")?"pressure":s.label.startsWith("Viento")?"windSpeed":s.label.startsWith("Ráfagas")?"windGust":"precipRate";s.data=data.map(x=>x[key]);}); chart("temperatureChart",data,[temp]);chart("humidityChart",data,[hum]);chart("pressureChart",data,[pre]);chart("windChart",data,[wind,gust]);chart("rainChart",data,[rain],"bar"); }
function rainTotal(data){const totals=data.filter(x=>Number.isFinite(x.precipTotal)).map(x=>x.precipTotal);if(totals.length<2)return null;let total=0,previous=null;totals.forEach(value=>{if(previous!==null)total+=value>=previous?value-previous:value;previous=value;});return total;}
function summary(data){const pressure=values(data,"pressure");const items=[["Máxima",stat(data,"temperature","max"),"°C"],["Mínima",stat(data,"temperature","min"),"°C"],["Humedad máxima",stat(data,"humidity","max"),"%"],["Ráfaga máxima",stat(data,"windGust","max"),"km/h"],["Lluvia",rainTotal(data),"mm"],["Variación presión",pressure.length>1?pressure.at(-1)-pressure[0]:null,"hPa"]].filter(x=>x[1]!==null);const el=document.getElementById("periodSummary");el.innerHTML=items.map(x=>`<article><span>${x[0]}</span><strong>${x[1].toFixed(1)} ${x[2]}</strong></article>`).join("");el.hidden=!items.length;}
async function load(period){document.getElementById("periodTitle").textContent=labels[period];document.querySelectorAll(".history-period").forEach(b=>{const a=b.dataset.period===period;b.classList.toggle("is-active",a);b.setAttribute("aria-pressed",a);});const status=document.getElementById("historyStatus");const summaryElement=document.getElementById("periodSummary");summaryElement.hidden=true;status.textContent="Cargando históricos…";try{let cached=chartCache.get(period);if(!cached||Date.now()-cached.time>CACHE_MS){const r=await fetch(`${History.API_BASE_URL}/api/history?${period}`,{cache:"no-store"});const body=await r.json();if(!r.ok||!body.ok)throw Error();cached={time:Date.now(),data:body.data};chartCache.set(period,cached);}if(!cached.data.length){status.textContent="Sin datos disponibles para este período.";destroyCharts();return;}status.textContent="";render(cached.data);summary(cached.data);}catch(e){status.textContent="Históricos temporalmente no disponibles.";destroyCharts();}}
async function info(){try{const r=await fetch(`${History.API_BASE_URL}/api/history/info`);const b=await r.json();if(b.ok&&b.data)document.getElementById("historyStart").textContent=`El histórico permanente comenzó a registrarse el ${History.formatDate(b.data.firstObservation,true)}.`;}catch(e){}}
document.querySelectorAll(".history-period").forEach(b=>b.addEventListener("click",()=>load(b.dataset.period)));info();load("hours=24");
