const History = window.MeteoHistoryConfig;
const HistoryApi = window.MeteoHistoryApi;
const DateTime = window.MeteoDateTime;
const chartCache = new Map();
const charts = {};
const statisticsCharts = {};
const CACHE_MS = 600000;
const PERIODS = { "24h": { history: "hours=24", label: "Últimas 24 horas" }, "7d": { history: "days=7", label: "Últimos 7 días" }, "30d": { history: "days=30", label: "Últimos 30 días" } };
let activePeriod = "24h";
let customDate = null;
let statisticsInfo = null;
let statisticsMode = "month";
function currentSelection() { return customDate ? { kind: "date", value: customDate } : { kind: "period", value: activePeriod }; }

function values(data, key) { return data.map((item) => item[key]).filter(Number.isFinite); }
function average(list) { return list.length ? list.reduce((total, value) => total + value, 0) / list.length : null; }
function stat(data, key, kind) { const list = values(data, key); return !list.length ? null : kind === "min" ? Math.min(...list) : kind === "max" ? Math.max(...list) : average(list); }
function format(value, unit) { return Number.isFinite(value) ? `${value.toFixed(1)} ${unit}` : "Sin datos"; }
function destroyCharts() { Object.values(charts).forEach((instance) => instance.destroy()); Object.keys(charts).forEach((key) => delete charts[key]); }
function directionLabel(data) { return !data.windDirection ? "" : `Dirección: ${data.windDirection}${Number.isFinite(data.windDirectionDegrees) ? ` (${Math.round(data.windDirectionDegrees)}°)` : ""}`; }
function chart(id, data, datasets, type, includeDirection, isDaily) {
  charts[id] = new window.Chart(document.getElementById(id), { type, data: { labels: data.map((item) => isDaily ? DateTime.formatTime(item.observedAt) : DateTime.formatShortDateTime(item.observedAt)), datasets }, options: { responsive: true, maintainAspectRatio: false, interaction: { mode: "index", intersect: false }, plugins: { legend: { display: datasets.length > 1 }, tooltip: { callbacks: { title: (context) => DateTime.formatDateTime(data[context[0].dataIndex].observedAt), afterBody: includeDirection ? (context) => directionLabel(data[context[0].dataIndex]) : undefined } } }, scales: { x: { ticks: { maxTicksLimit: 6, color: History.COLORS.muted }, grid: { display: false } }, y: { ticks: { color: History.COLORS.muted }, grid: { color: "rgba(97,115,129,.12)" } } } } });
}
function series(label, key, color, fill = false) { return { label, key, data: [], borderColor: color, backgroundColor: fill ? "rgba(25,118,185,.12)" : color, borderWidth: 2, pointRadius: 0, tension: .25, fill }; }
function render(data) {
  destroyCharts();
  const datasets = [series("Temperatura °C", "temperature", History.COLORS.blue, true), series("Humedad %", "humidity", History.COLORS.blue), series("Presión hPa", "pressure", History.COLORS.navy), series("Viento km/h", "windSpeed", History.COLORS.blue), series("Ráfagas km/h", "windGust", History.COLORS.gust), { label: "Intensidad mm/h", key: "precipRate", data: [], backgroundColor: History.COLORS.rain, borderColor: History.COLORS.rain }];
  datasets.forEach((dataset) => { dataset.data = data.map((item) => item[dataset.key]); delete dataset.key; });
  const daily = customDate !== null || activePeriod === "24h";
  chart("temperatureChart", data, [datasets[0]], "line", false, daily); chart("humidityChart", data, [datasets[1]], "line", false, daily); chart("pressureChart", data, [datasets[2]], "line", false, daily); chart("windChart", data, [datasets[3], datasets[4]], "line", true, daily); chart("rainChart", data, [datasets[5]], "bar", false, daily);
}
function rainTotal(data) { const totals = values(data, "precipTotal"); return totals.length < 2 ? null : totals.reduce((total, value, index) => index ? total + (value >= totals[index - 1] ? value - totals[index - 1] : value) : total, 0); }
function setCards(id, cards) { const element = document.getElementById(id); element.innerHTML = cards.map(([label, value]) => `<article><span>${label}</span><strong>${value}</strong></article>`).join(""); element.hidden = !cards.length; }
function summary(data) { const pressure = values(data, "pressure"); setCards("periodSummary", [["Máxima", format(stat(data, "temperature", "max"), "°C")], ["Mínima", format(stat(data, "temperature", "min"), "°C")], ["Humedad máxima", format(stat(data, "humidity", "max"), "%")], ["Ráfaga máxima", format(stat(data, "windGust", "max"), "km/h")], ["Lluvia", format(rainTotal(data), "mm")], ["Variación presión", pressure.length > 1 ? format(pressure.at(-1) - pressure[0], "hPa") : "Sin datos"]]); }
function comparisonCards(current, previous) {
  const metrics = [["Temperatura media", "temperatureAvg", "°C"], ["Temperatura máxima", "temperatureMax", "°C"], ["Temperatura mínima", "temperatureMin", "°C"], ["Humedad media", "humidityAvg", "%"], ["Presión media", "pressureAvg", "hPa"], ["Viento medio", "windAvg", "km/h"], ["Ráfaga máxima", "windGustMax", "km/h"], ["Precipitación", "precipitation", "mm"]];
  return metrics.filter(([, key]) => Number.isFinite(current[key]) && Number.isFinite(previous[key])).map(([label, key, unit]) => { const delta = current[key] - previous[key]; const icon = delta > 0 ? "fa-arrow-up" : delta < 0 ? "fa-arrow-down" : "fa-minus"; return `<article class="comparison-card"><span>${label}</span><strong>${format(current[key], unit)}</strong><small>Anterior: ${format(previous[key], unit)}</small><span class="comparison-change"><i class="fa-solid ${icon}" aria-hidden="true"></i>${delta >= 0 ? "+" : ""}${delta.toFixed(1)} ${unit}</span></article>`; });
}
async function loadComparison() {
  const status = document.getElementById("compareStatus"); const grid = document.getElementById("comparisonGrid");
  if (customDate) { status.textContent = "La comparativa está disponible para los períodos predefinidos."; grid.hidden = true; return; }
  status.textContent = "Cargando comparativa…";
  try { const result = await HistoryApi.fetchCompare(activePeriod); const cards = result.sufficient ? comparisonCards(result.current, result.previous) : []; grid.innerHTML = cards.join(""); grid.hidden = !cards.length; status.textContent = cards.length ? "" : "Aún no hay datos suficientes para comparar ambos períodos."; } catch (error) { console.error("No se pudo cargar la comparativa:", error); grid.hidden = true; status.textContent = "Comparativa temporalmente no disponible."; }
}
function dailyNarrative(data, currentDay) { if (!data) return ""; const range = Number.isFinite(data.temperature && data.temperature.min) && Number.isFinite(data.temperature && data.temperature.max) ? `${currentDay ? "En lo que va del día" : "Durante este día"} la temperatura se movió entre ${format(data.temperature.min, "°C")} y ${format(data.temperature.max, "°C")}.` : "Hay observaciones meteorológicas disponibles para esta fecha."; const gust = Number.isFinite(data.gust && data.gust.max) ? ` La ráfaga máxima alcanzó ${format(data.gust.max, "km/h")}.` : ""; const rain = Number.isFinite(data.precipitation && data.precipitation.total) ? data.precipitation.total > 0 ? ` Se acumularon ${format(data.precipitation.total, "mm")} de precipitación.` : " No se registraron precipitaciones." : ""; return `${range}${gust}${rain}`; }
async function loadToday(date) { const status = document.getElementById("todayStatus"); const summary = document.getElementById("todaySummary"); const narrative = document.getElementById("todayNarrative"); try { const result = await HistoryApi.fetchDailySummary(date); const data = result.data; document.getElementById("today-title").textContent = date ? `Resumen: ${DateTime.formatDate(`${date}T12:00:00-03:00`)}` : "Condiciones registradas hoy"; if (!data) { status.textContent = "No hay datos disponibles para esta fecha."; summary.hidden = true; narrative.textContent = ""; return; } setCards("todaySummary", [["Temperatura máxima", `${format(data.temperature.max, "°C")} · ${data.temperature.maxAt ? DateTime.formatTime(data.temperature.maxAt) : "sin hora"}`], ["Temperatura mínima", `${format(data.temperature.min, "°C")} · ${data.temperature.minAt ? DateTime.formatTime(data.temperature.minAt) : "sin hora"}`], ["Humedad", `${format(data.humidity.min, "%")} – ${format(data.humidity.max, "%")}`], ["Presión", `${format(data.pressure.min, "hPa")} – ${format(data.pressure.max, "hPa")}`], ["Viento máximo", `${format(data.wind.max, "km/h")} · ${data.wind.maxAt ? DateTime.formatTime(data.wind.maxAt) : "sin hora"}`], ["Ráfaga máxima", `${format(data.gust.max, "km/h")} · ${data.gust.maxAt ? DateTime.formatTime(data.gust.maxAt) : "sin hora"}`], ["Precipitación", format(data.precipitation.total, "mm")], ["Cobertura", `${data.coverage.percentage} % · ${data.observations} observaciones`]]); narrative.textContent = `${dailyNarrative(data, result.isCurrentDay)}${data.coverage.partial && data.firstObservation ? ` Datos disponibles desde ${DateTime.formatTime(data.firstObservation)}; cobertura parcial.` : ""}`; status.textContent = ""; } catch (error) { console.error("No se pudo cargar el resumen diario:", error); summary.hidden = true; status.textContent = "Resumen diario temporalmente no disponible."; } }
function recordCard(label, value, at, unit) { return `<article class="record-item"><span>${label}</span><strong>${format(value, unit)}</strong><span>${at ? DateTime.formatDateTime(at) : "Sin fecha disponible"}</span></article>`; }
function formatDateOnly(value) { return value ? DateTime.formatDate(`${value}T12:00:00-03:00`) : "Sin fecha disponible"; }
function statisticLabel(mode, value) { if (mode === "all") return "Todo el histórico disponible"; if (mode === "year") return value; return new Intl.DateTimeFormat("es-AR", { month: "long", year: "numeric", timeZone: "America/Argentina/Buenos_Aires" }).format(new Date(`${value}-01T12:00:00-03:00`)); }
function statisticOptions() {
  const select = document.getElementById("statisticsValue"); const label = document.getElementById("statisticsValueLabel");
  if (!statisticsInfo || statisticsMode === "all") { label.hidden = true; return; }
  const values = statisticsMode === "month" ? statisticsInfo.months : statisticsInfo.years;
  const today = DateTime.formatDate(new Date()).split("/").reverse().join("-"); const current = statisticsMode === "month" ? today.slice(0, 7) : today.slice(0, 4);
  const previous = statisticsMode === "month" ? (() => { const [year, month] = current.split("-").map(Number); return new Date(Date.UTC(year, month - 2, 1)).toISOString().slice(0, 7); })() : String(Number(current) - 1);
  const selected = values.includes(select.value) ? select.value : (values.includes(current) ? current : values.at(-1));
  select.innerHTML = "";
  values.slice().reverse().forEach((value) => { const option = document.createElement("option"); option.value = value; const prefix = value === current ? statisticsMode === "month" ? "Mes actual — " : "Año en curso — " : value === previous ? "Anterior — " : ""; option.textContent = `${prefix}${statisticLabel(statisticsMode, value)}`; select.appendChild(option); });
  select.value = selected; label.hidden = false; label.firstChild.textContent = statisticsMode === "month" ? "Mes disponible" : "Año disponible";
}
function destroyStatisticsCharts() { Object.values(statisticsCharts).forEach((instance) => instance.destroy()); Object.keys(statisticsCharts).forEach((key) => delete statisticsCharts[key]); }
function renderStatisticsCharts(daily) {
  const container = document.querySelector(".statistics-charts"); destroyStatisticsCharts();
  if (!daily || !daily.length || !window.Chart) { container.hidden = true; return; }
  container.hidden = false; const labels = daily.map((day) => formatDateOnly(day.date));
  const options = { responsive: true, maintainAspectRatio: false, interaction: { mode: "index", intersect: false }, plugins: { legend: { display: true } }, scales: { x: { ticks: { maxTicksLimit: 8, color: History.COLORS.muted }, grid: { display: false } }, y: { ticks: { color: History.COLORS.muted }, grid: { color: "rgba(97,115,129,.12)" } } } };
  statisticsCharts.temperature = new window.Chart(document.getElementById("dailyTemperatureChart"), { type: "line", data: { labels, datasets: [{ label: "Máxima °C", data: daily.map((day) => day.temperatureMax), borderColor: History.COLORS.gust, backgroundColor: History.COLORS.gust, borderWidth: 2, pointRadius: 2, tension: .25 }, { label: "Media °C", data: daily.map((day) => day.temperatureAvg), borderColor: History.COLORS.blue, backgroundColor: History.COLORS.blue, borderWidth: 2, pointRadius: 2, tension: .25 }, { label: "Mínima °C", data: daily.map((day) => day.temperatureMin), borderColor: History.COLORS.navy, backgroundColor: History.COLORS.navy, borderWidth: 2, pointRadius: 2, tension: .25 }] }, options });
  statisticsCharts.precipitation = new window.Chart(document.getElementById("dailyPrecipitationChart"), { type: "bar", data: { labels, datasets: [{ label: "Precipitación mm", data: daily.map((day) => day.precipitation), backgroundColor: History.COLORS.rain, borderColor: History.COLORS.rain }] }, options });
}
function statisticsNarrative(data, label, partial) { if (!data) return ""; const temperature = data.temperature; const range = Number.isFinite(temperature.min) && Number.isFinite(temperature.max) ? `Los registros disponibles de ${label} muestran una temperatura entre ${format(temperature.min, "°C")} y ${format(temperature.max, "°C")}.` : `Hay observaciones disponibles para ${label}.`; const gust = Number.isFinite(data.gust.max) ? ` La ráfaga máxima alcanzó ${format(data.gust.max, "km/h")}.` : ""; const rain = Number.isFinite(data.precipitation.total) ? data.precipitation.total > 0 ? ` Se acumularon ${format(data.precipitation.total, "mm")} de precipitación.` : " No se registraron precipitaciones." : ""; const coverage = partial || data.coverage.level !== "good" ? ` Cobertura ${data.coverage.percentage} %: los resultados representan los datos disponibles.` : ""; return `${range}${gust}${rain}${coverage}`; }
function statisticsComparison(current, previous) { const metrics = [["Temperatura media registrada", current.temperature.average, previous.temperature.average, "°C"], ["Temperatura máxima", current.temperature.max, previous.temperature.max, "°C"], ["Temperatura mínima", current.temperature.min, previous.temperature.min, "°C"], ["Precipitación", current.precipitation.total, previous.precipitation.total, "mm"], ["Ráfaga máxima", current.gust.max, previous.gust.max, "km/h"]]; return metrics.filter(([, now, before]) => Number.isFinite(now) && Number.isFinite(before)).map(([label, now, before, unit]) => { const delta = now - before; const icon = delta > 0 ? "fa-arrow-up" : delta < 0 ? "fa-arrow-down" : "fa-minus"; return `<article class="comparison-card"><span>${label}</span><strong>${format(now, unit)}</strong><small>Anterior: ${format(before, unit)}</small><span class="comparison-change"><i class="fa-solid ${icon}" aria-hidden="true"></i>${delta >= 0 ? "+" : ""}${delta.toFixed(1)} ${unit}</span></article>`; }).join(""); }
async function loadStatistics() {
  const status = document.getElementById("statisticsStatus"); const summary = document.getElementById("statisticsSummary"); const range = document.getElementById("statisticsRange"); const narrative = document.getElementById("statisticsNarrative"); const compareStatus = document.getElementById("statisticsCompareStatus"); const compareGrid = document.getElementById("statisticsComparisonGrid");
  if (!statisticsInfo) return; const value = statisticsMode === "all" ? "" : document.getElementById("statisticsValue").value; status.textContent = "Calculando estadísticas con registros reales…"; summary.hidden = true; range.textContent = ""; narrative.textContent = ""; compareGrid.hidden = true;
  try { const result = await HistoryApi.fetchStatistics(statisticsMode, value); const data = result.data; if (!data) { status.textContent = "No hay datos disponibles para este período."; destroyStatisticsCharts(); document.querySelector(".statistics-charts").hidden = true; return; }
    const label = statisticLabel(statisticsMode, result.value); const available = statisticsMode === "all" ? `Período disponible: ${DateTime.formatDateTime(data.firstObservation)} — ${DateTime.formatDateTime(data.lastObservation)}.` : `${statisticsMode === "year" && result.range.partial ? "Año en curso. " : ""}Datos disponibles: ${DateTime.formatDateTime(data.firstObservation)} — ${DateTime.formatDateTime(data.lastObservation)}.`;
    range.textContent = available;
    setCards("statisticsSummary", [["Temperatura máxima", `${format(data.temperature.max, "°C")} · ${data.temperature.maxAt ? DateTime.formatDateTime(data.temperature.maxAt) : "sin hora"}`], ["Temperatura mínima", `${format(data.temperature.min, "°C")} · ${data.temperature.minAt ? DateTime.formatDateTime(data.temperature.minAt) : "sin hora"}`], ["Temperatura media registrada", format(data.temperature.average, "°C")], ["Humedad (máx. / mín. / media)", `${format(data.humidity.max, "%")} / ${format(data.humidity.min, "%")} / ${format(data.humidity.average, "%")}`], ["Presión (máx. / mín. / media)", `${format(data.pressure.max, "hPa")} / ${format(data.pressure.min, "hPa")} / ${format(data.pressure.average, "hPa")}`], ["Ráfaga máxima", `${format(data.gust.max, "km/h")} · ${data.gust.maxAt ? DateTime.formatDateTime(data.gust.maxAt) : "sin hora"}`], ["Precipitación acumulada", format(data.precipitation.total, "mm")], ["Día más lluvioso", data.precipitation.wettestDay ? `${formatDateOnly(data.precipitation.wettestDay.date)} · ${format(data.precipitation.wettestDay.total, "mm")}` : "Sin lluvia registrada"], ["Días con precipitación", String(data.precipitation.rainyDays)], ["Cobertura aproximada", `${data.coverage.percentage} % · ${data.observations} observaciones`]]);
    narrative.textContent = statisticsNarrative(data, label, result.range.partial); renderStatisticsCharts(data.daily); status.textContent = "";
    const comparison = result.comparison; const cards = comparison && comparison.sufficient ? statisticsComparison(data, comparison.data) : ""; compareGrid.innerHTML = cards; compareGrid.hidden = !cards; compareStatus.textContent = cards ? `${comparison.sameElapsed ? "Comparación hasta el mismo momento relativo del período anterior." : "Comparación con el período calendario anterior."}` : comparison ? "La comparación estará disponible cuando ambos períodos alcancen al menos 50 % de cobertura." : "No existe un período anterior equivalente para comparar.";
  } catch (error) { console.error("No se pudieron cargar las estadísticas:", error); status.textContent = "Estadísticas temporalmente no disponibles."; destroyStatisticsCharts(); document.querySelector(".statistics-charts").hidden = true; compareStatus.textContent = "Comparativa estadística temporalmente no disponible."; }
}
async function loadRecords() { const status = document.getElementById("recordsStatus"); try { const data = await HistoryApi.fetchRecords(); if (!data) { status.textContent = "Aún no hay récords disponibles."; return; } const wettest = data.precipitation && data.precipitation.wettestDay; document.getElementById("recordsGrid").innerHTML = [recordCard("Temperatura máxima", data.temperature.max, data.temperature.maxAt, "°C"), recordCard("Temperatura mínima", data.temperature.min, data.temperature.minAt, "°C"), recordCard("Ráfaga máxima", data.windGust.max, data.windGust.maxAt, "km/h"), wettest ? `<article class="record-item"><span>Día más lluvioso</span><strong>${format(wettest.total, "mm")}</strong><span>${formatDateOnly(wettest.date)}</span></article>` : "", recordCard("Presión máxima", data.pressure.max, data.pressure.maxAt, "hPa"), recordCard("Presión mínima", data.pressure.min, data.pressure.minAt, "hPa"), recordCard("Humedad máxima", data.humidity.max, data.humidity.maxAt, "%"), recordCard("Humedad mínima", data.humidity.min, data.humidity.minAt, "%")].join(""); document.getElementById("recordsGrid").hidden = false; status.textContent = `Récords de la estación desde ${DateTime.formatDate(data.firstObservation)}.`; } catch (error) { console.error("No se pudieron cargar los récords:", error); status.textContent = "Récords temporalmente no disponibles."; } }
async function loadInfo() { try { const data = await HistoryApi.fetchInfo(); if (!data) return; document.getElementById("historyDate").min = data.firstObservation.slice(0, 10); document.getElementById("historyDate").max = DateTime.formatDate(new Date()).split("/").reverse().join("-"); setCards("historyQuality", [["Observaciones registradas", String(data.totalObservations)], ["Primera observación", DateTime.formatDateTime(data.firstObservation)], ["Última observación", DateTime.formatDateTime(data.lastObservation)]]); } catch (error) { console.error("No se pudo consultar la información del histórico:", error); } }
function updateControls() { const custom = customDate !== null; document.querySelectorAll(".history-period").forEach((button) => { const active = !custom && button.dataset.period === activePeriod; button.classList.toggle("is-active", active); button.setAttribute("aria-pressed", String(active)); }); document.getElementById("resetHistory").hidden = !custom; document.getElementById("periodTitle").textContent = custom ? `Fecha: ${DateTime.formatDate(`${customDate}T12:00:00-03:00`)}` : PERIODS[activePeriod].label; }
async function load() { const selected = currentSelection(); updateControls(); loadComparison(); loadToday(selected.kind === "date" ? selected.value : undefined); const status = document.getElementById("historyStatus"); document.getElementById("periodSummary").hidden = true; status.textContent = "Cargando históricos…"; try { const cacheKey = `${selected.kind}:${selected.value}`; let data = chartCache.get(cacheKey); if (!data || Date.now() - data.time > CACHE_MS) { const rows = selected.kind === "date" ? await HistoryApi.fetchDate(selected.value) : await HistoryApi.fetchHistory(PERIODS[activePeriod].history); data = { time: Date.now(), rows }; chartCache.set(cacheKey, data); } if (!data.rows.length) { destroyCharts(); status.textContent = selected.kind === "date" ? "No existen observaciones registradas para esta fecha." : "Sin datos disponibles para este período."; return; } render(data.rows); summary(data.rows); status.textContent = ""; } catch (error) { console.error("No se pudieron cargar los históricos:", error); destroyCharts(); status.textContent = "Históricos temporalmente no disponibles."; } }
function exportFilename(selected) { const today = DateTime.formatDate(new Date()).split("/").reverse().join("-"); return selected.kind === "date" ? `meteoituzaingo_${selected.value}.csv` : `meteoituzaingo_${selected.value}_${today}.csv`; }
async function exportCsv() { const button = document.getElementById("exportCsv"); const status = document.getElementById("csvStatus"); const selected = currentSelection(); if (selected.kind === "period" && !Object.hasOwn(PERIODS, activePeriod)) { status.hidden = false; status.textContent = "No se pudo generar el archivo CSV: período inválido."; return; } button.disabled = true; status.hidden = false; status.textContent = "Generando CSV…"; try { const response = await fetch(HistoryApi.exportUrl(selected), { cache: "no-store" }); const contentType = response.headers.get("Content-Type") || ""; if (!response.ok || !contentType.includes("text/csv")) throw new Error(`Exportación CSV falló (${response.status})`); const blob = await response.blob(); const url = URL.createObjectURL(blob); const link = document.createElement("a"); link.href = url; link.download = exportFilename(selected); document.body.appendChild(link); link.click(); link.remove(); URL.revokeObjectURL(url); status.textContent = "CSV descargado correctamente."; } catch (error) { console.error("No se pudo exportar el CSV:", error); status.textContent = "No se pudo generar el archivo CSV."; } finally { button.disabled = false; } }
document.querySelectorAll(".history-period").forEach((button) => button.addEventListener("click", () => { activePeriod = button.dataset.period; customDate = null; document.getElementById("historyDate").value = ""; load(); }));
document.getElementById("historyDate").addEventListener("change", (event) => { if (!event.target.value) return; customDate = event.target.value; load(); });
document.getElementById("resetHistory").addEventListener("click", () => { activePeriod = "24h"; customDate = null; document.getElementById("historyDate").value = ""; load(); });
document.getElementById("exportCsv").addEventListener("click", exportCsv);
document.querySelectorAll(".statistics-mode").forEach((button) => button.addEventListener("click", () => { statisticsMode = button.dataset.statisticsMode; document.querySelectorAll(".statistics-mode").forEach((item) => { const active = item === button; item.classList.toggle("is-active", active); item.setAttribute("aria-pressed", String(active)); }); statisticOptions(); loadStatistics(); }));
document.getElementById("statisticsValue").addEventListener("change", loadStatistics);
async function loadStatisticsInfo() { try { statisticsInfo = await HistoryApi.fetchStatisticsInfo(); if (!statisticsInfo) { document.getElementById("statisticsStatus").textContent = "Aún no hay datos suficientes para estadísticas."; return; } statisticOptions(); loadStatistics(); } catch (error) { console.error("No se pudo consultar la disponibilidad estadística:", error); document.getElementById("statisticsStatus").textContent = "Estadísticas temporalmente no disponibles."; } }
loadInfo(); loadRecords(); loadStatisticsInfo(); load();
