import assert from "node:assert/strict";
import { DatabaseSync } from "node:sqlite";
import { readFile } from "node:fs/promises";

const db = new DatabaseSync(":memory:");
for (const migration of ["0001_create_weather_observations.sql", "0007_create_weather_rollups.sql", "0008_add_weather_rollup_control_state.sql", "0009_add_weather_rollup_fencing.sql"]) db.exec(await readFile(new URL(`../migrations/${migration}`, import.meta.url), "utf8"));
const columns = db.prepare("PRAGMA table_info(weather_rollup_state)").all();
for (const name of ["backfill_lease_token", "backfill_fence", "canonical_revision", "validation_canonical_revision"]) assert.ok(columns.some((column) => column.name === name), `${name} existe`);
const state = () => db.prepare("SELECT * FROM weather_rollup_state WHERE id=1").get();
assert.equal(state().backfill_fence, 0);
assert.equal(state().canonical_revision, 0);
assert.equal(state().backfill_lease_token, null);
assert.equal(state().validation_canonical_revision, null);
assert.equal(db.prepare("SELECT name FROM sqlite_master WHERE type='trigger' AND name='weather_observations_rollup_revision'").get().name, "weather_observations_rollup_revision");
const insert = db.prepare(`INSERT INTO weather_observations (observed_at, temperature, feels_like, humidity, pressure, wind_speed, wind_gust, wind_direction, wind_direction_degrees, precip_rate, precip_total, dew_point, weather_condition, created_at) VALUES (?, 20, 20, 50, 1000, 10, 20, 'N', 0, 0, 1, 10, NULL, ?)`);
const stamp = (observedAt) => insert.run(observedAt, "2026-10-08T00:00:00.000Z");
db.prepare("UPDATE weather_rollup_state SET status='ready', validation_cursor_observed_at='cursor', validation_passed_at='pass', validation_canonical_revision=7 WHERE id=1").run();
stamp("2026-01-01T03:00:00.000Z");
assert.equal(state().canonical_revision, 1);
assert.equal(state().dirty_from_local_date, "2026-01-01");
assert.equal(state().status, "repairing");
assert.equal(state().validation_cursor_observed_at, null);
assert.equal(state().validation_passed_at, null);
assert.equal(state().validation_canonical_revision, null);
db.prepare("UPDATE weather_rollup_state SET status='pending_backfill', validation_cursor_observed_at='keep', validation_passed_at='keep', validation_canonical_revision=1 WHERE id=1").run();
db.prepare("INSERT OR IGNORE INTO weather_observations (observed_at, temperature, created_at) VALUES (?, 20, ?)").run("2026-01-01T03:00:00.000Z", "2026-10-08T00:00:00.000Z");
assert.equal(state().canonical_revision, 1, "INSERT OR IGNORE no incrementa revision");
assert.equal(state().status, "pending_backfill");
assert.equal(state().validation_cursor_observed_at, "keep");
stamp("2026-01-01T02:50:00.000Z");
assert.equal(state().canonical_revision, 2, "insercion historica incrementa revision");
assert.equal(state().dirty_from_local_date, "2025-12-31", "medianoche ART usa UTC-03");
assert.equal(state().status, "pending_backfill", "pending se preserva");
db.prepare("UPDATE weather_rollup_state SET dirty_from_local_date=NULL WHERE id=1").run();
stamp("2026-02-01T02:59:00.000Z");
assert.equal(state().dirty_from_local_date, "2026-01-31", "cambio de mes ART");
db.prepare("UPDATE weather_rollup_state SET dirty_from_local_date=NULL WHERE id=1").run();
stamp("2027-01-01T02:59:00.000Z");
assert.equal(state().dirty_from_local_date, "2026-12-31", "cambio de anio ART");
const revisionBeforeInvalid = state().canonical_revision;
assert.throws(() => stamp("fecha-invalida"), /invalid observed_at for rollup revision/);
assert.equal(state().canonical_revision, revisionBeforeInvalid, "timestamp invalido revierte INSERT y trigger");
const revisionBeforeRollback = state().canonical_revision;
db.exec("BEGIN"); stamp("2027-01-01T03:10:00.000Z"); db.exec("ROLLBACK");
assert.equal(state().canonical_revision, revisionBeforeRollback, "rollback revierte revision canonica");
assert.equal(db.prepare("SELECT COUNT(*) AS count FROM weather_observations WHERE observed_at='2027-01-01T03:10:00.000Z'").get().count, 0);
db.close();
console.log("weather rollup fencing schema tests: OK");
