import assert from "node:assert/strict";
import worker from "../src/index.js";
import { acquireBackfillLease, finalizeControlledBackfill, readRollupStatus, releaseBackfillLease, runControlledBackfill, validateControlledBackfill } from "../src/weather-rollup-runner.js";

const NOW = new Date("2026-10-07T12:00:00.000Z");
class FakeDb {
  constructor() { this.state = { id: 1, status: "backfilling", observation_count: 250, rollup_cursor_observed_at: "2026-10-07T11:50:00.000Z", backfill_lease_until: null, validation_cursor_observed_at: null, validation_passed_at: null }; this.newer = false; this.rawQueries = 0; }
  prepare(sql) { const db = this; const statement = (values = []) => ({ first: async () => { if (sql.startsWith("SELECT id, status")) return structuredClone(db.state); if (sql.startsWith("SELECT observed_at FROM weather_observations")) { db.rawQueries += 1; return db.newer ? { observed_at: "2026-10-07T12:00:00.000Z" } : null; } throw new Error(`FIRST no simulado: ${sql}`); }, run: async () => { if (sql.startsWith("UPDATE weather_rollup_state SET backfill_lease_until=?")) { const [until, now] = values; const available = !db.state.backfill_lease_until || db.state.backfill_lease_until <= now; if (available) db.state.backfill_lease_until = until; return { meta: { changes: available ? 1 : 0 } }; } if (sql.startsWith("UPDATE weather_rollup_state SET backfill_lease_until=NULL")) { const owned = db.state.backfill_lease_until === values[0]; if (owned) db.state.backfill_lease_until = null; return { meta: { changes: owned ? 1 : 0 } }; } if (sql.startsWith("UPDATE weather_rollup_state SET validation_cursor_observed_at=NULL")) { db.state.validation_cursor_observed_at = null; db.state.validation_passed_at = null; return { meta: { changes: 1 } }; } if (sql.startsWith("UPDATE weather_rollup_state SET validation_cursor_observed_at=?")) { const allowed = db.state.rollup_cursor_observed_at === values[3] && (!db.state.backfill_lease_until || db.state.backfill_lease_until <= values[4]); if (allowed) { db.state.validation_cursor_observed_at = values[0]; db.state.validation_passed_at = values[1]; } return { meta: { changes: allowed ? 1 : 0 } }; } if (sql.startsWith("UPDATE weather_rollup_state SET status='ready'")) { const allowed = !db.newer && db.state.rollup_cursor_observed_at && db.state.validation_cursor_observed_at === db.state.rollup_cursor_observed_at && db.state.validation_passed_at && (!db.state.backfill_lease_until || db.state.backfill_lease_until <= values[1]); if (allowed) db.state.status = "ready"; return { meta: { changes: allowed ? 1 : 0 } }; } throw new Error(`RUN no simulado: ${sql}`); } }); const base = statement(); base.bind = (...values) => statement(values); return base; }
}
const db = new FakeDb();
assert.equal((await acquireBackfillLease(db, NOW)).acquired, true); const leaseA = db.state.backfill_lease_until; assert.equal((await acquireBackfillLease(db, NOW)).acquired, false, "lease activo rechaza segundo runner"); db.state.backfill_lease_until = new Date(NOW.getTime() - 1).toISOString(); assert.equal((await acquireBackfillLease(db, new Date(NOW.getTime() + 1))).acquired, true, "lease vencido se recupera"); const leaseB = db.state.backfill_lease_until; assert.notEqual(leaseA, leaseB); assert.equal(await releaseBackfillLease(db, leaseA), false, "runner viejo no libera lease nuevo"); assert.equal(await releaseBackfillLease(db, leaseB), true);
let calls = 0; const batch = await runControlledBackfill(db, { now: NOW, runBatch: async (_database, options) => { calls += 1; assert.equal(options.batchSize, 250); return { processed: 250, complete: false, cursor: db.state.rollup_cursor_observed_at }; } }); assert.equal(batch.ok, true); assert.equal(calls, 1); assert.equal(db.state.backfill_lease_until, null);
await assert.rejects(() => runControlledBackfill(db, { now: NOW, runBatch: async () => { throw new Error("fallo controlado"); } })); assert.equal(db.state.backfill_lease_until, null, "error libera sÃ³lo lease propio");
assert.equal((await readRollupStatus(db)).rollup_cursor_observed_at, db.state.rollup_cursor_observed_at); assert.equal(db.rawQueries, 0, "status no consulta observaciones");
db.state.validation_cursor_observed_at = "old"; db.state.validation_passed_at = "old"; const passed = await validateControlledBackfill(db, { now: NOW, validate: async () => ({ ok: true, mismatches: [] }) }); assert.equal(passed.ok, true); assert.equal(db.state.validation_cursor_observed_at, db.state.rollup_cursor_observed_at); assert.equal(db.state.status, "backfilling", "validar no finaliza"); const failed = await validateControlledBackfill(db, { now: NOW, validate: async () => ({ ok: false, mismatches: ["daily.test"] }) }); assert.equal(failed.ok, false); assert.equal(db.state.validation_cursor_observed_at, null); assert.equal(db.state.validation_passed_at, null);
assert.equal((await finalizeControlledBackfill(db, NOW)).ok, false, "sin validaciÃ³n no finaliza"); db.state.validation_cursor_observed_at = "other"; db.state.validation_passed_at = NOW.toISOString(); assert.equal((await finalizeControlledBackfill(db, NOW)).ok, false, "cursor distinto no finaliza"); db.state.validation_cursor_observed_at = db.state.rollup_cursor_observed_at; db.state.backfill_lease_until = new Date(NOW.getTime() + 60000).toISOString(); assert.equal((await finalizeControlledBackfill(db, NOW)).ok, false, "lease activo no finaliza"); db.state.backfill_lease_until = null; db.newer = true; assert.equal((await finalizeControlledBackfill(db, NOW)).ok, false, "observaciÃ³n nueva no procesada no finaliza"); db.newer = false; assert.equal((await finalizeControlledBackfill(db, NOW)).ok, true); assert.equal(db.state.status, "ready");
for (const path of ["status", "backfill", "validate", "finalize"]) { const method = path === "status" ? "GET" : "POST"; const response = await worker.fetch(new Request(`https://worker.example/api/admin/weather-rollups/${path}`, { method }), { ALLOWED_ORIGINS: "https://gerchop.github.io" }); assert.equal(response.status, 401, `${path} exige ADMIN_TOKEN`); }
const source = await (await import("node:fs/promises")).readFile(new URL("../src/weather-rollups.js", import.meta.url), "utf8"); assert.match(source, /validation_cursor_observed_at=NULL, validation_passed_at=NULL/);
console.log("weather rollup runner tests: OK (auth, lease, one batch, frontier, validation and finalize)");