import assert from "node:assert/strict";
import { aggregateRows, backfillBatch, finalizeBackfill, localDate, runBackfill, validateDatabaseEquivalence, validateEquivalence, validatePeriodStatistics } from "../src/weather-rollups.js";

const COLUMNS = ["local_date", "first_observed_at", "last_observed_at", "observation_count", "temperature_count", "temperature_sum", "temperature_min", "temperature_min_at", "temperature_max", "temperature_max_at", "humidity_count", "humidity_sum", "humidity_min", "humidity_min_at", "humidity_max", "humidity_max_at", "pressure_count", "pressure_sum", "pressure_min", "pressure_min_at", "pressure_max", "pressure_max_at", "wind_count", "wind_sum", "wind_max", "wind_max_at", "gust_max", "gust_max_at", "precipitation_total", "precipitation_sample_count", "last_precip_total", "last_precip_observed_at", "updated_at"];
function row(observed_at, overrides = {}) { return { observed_at, temperature: 10, humidity: 50, pressure: 1000, wind_speed: 10, wind_gust: 20, precip_total: null, ...overrides }; }
const FIXTURES = [
  row("2025-12-31T02:50:00.000Z", { temperature: 20, wind_gust: 30, precip_total: 2 }),
  row("2026-01-01T03:00:00.000Z", { temperature: 20, wind_gust: 30, precip_total: 1 }),
  row("2026-01-01T03:10:00.000Z", { temperature: 12, precip_total: 2 }),
  row("2026-01-01T03:20:00.000Z", { temperature: 8, precip_total: .5 }),
  row("2026-01-01T03:30:00.000Z", { temperature: 9, precip_total: 1.5 }),
  row("2026-01-01T03:40:00.000Z", { temperature: 9, precip_total: .2 }),
  row("2026-01-01T03:50:00.000Z", { temperature: 7, precip_total: .4, humidity: null, pressure: 1200 }),
  row("2026-02-01T03:00:00.000Z", { temperature: -1, wind_gust: 35, precip_total: 3 }),
  row("2027-01-01T03:00:00.000Z", { temperature: 15, precip_total: null })
];
class FakeD1 {
  constructor(rows) { this.rows = structuredClone(rows); this.state = { id: 1, first_observed_at: null, last_observed_at: null, observation_count: 0, rollup_cursor_observed_at: null, dirty_from_local_date: null, status: "pending_backfill", last_reconciled_at: null, updated_at: null }; this.days = new Map(); this.records = new Map(); }
  prepare(sql) { const db = this; const query = (values) => { if (sql.startsWith("SELECT * FROM weather_rollup_state")) return db.state; if (sql.startsWith("SELECT * FROM weather_observations WHERE")) { const [cursor,, limit] = values; return { results: db.rows.filter((item) => !cursor || item.observed_at > cursor).sort((a, b) => a.observed_at.localeCompare(b.observed_at)).slice(0, limit) }; } if (sql === "SELECT * FROM weather_observations ORDER BY observed_at ASC") return { results: structuredClone(db.rows).sort((a, b) => a.observed_at.localeCompare(b.observed_at)) }; if (sql.startsWith("SELECT * FROM weather_daily_aggregates WHERE")) return db.days.get(values[0]) || null; if (sql === "SELECT * FROM weather_daily_aggregates ORDER BY local_date ASC") return { results: [...db.days.values()].sort((a, b) => a.local_date.localeCompare(b.local_date)) }; if (sql === "SELECT * FROM weather_record_values") return { results: [...db.records.values()] }; if (sql === "SELECT * FROM weather_record_values ORDER BY metric ASC") return { results: [...db.records.values()].sort((a, b) => a.metric.localeCompare(b.metric)) }; throw new Error(`SQL no simulado: ${sql}`); }; const statement = (values = []) => ({ sql, values, first: async () => query(values), all: async () => { const result = query(values); return result?.results ? result : { results: result ? [result] : [] }; }, run: async () => { if (sql.startsWith("UPDATE weather_rollup_state SET status='ready'")) { db.state.status = "ready"; db.state.last_reconciled_at = values[0]; db.state.updated_at = values[1]; return { meta: { changes: 1 } }; } throw new Error(`RUN no simulado: ${sql}`); } }); const base = statement(); base.bind = (...values) => statement(values); return base; }
  async batch(statements) { for (const item of statements) { if (item.sql.startsWith("INSERT INTO weather_daily_aggregates")) { const day = Object.fromEntries(COLUMNS.map((key, index) => [key, item.values[index]])); this.days.set(day.local_date, day); } else if (item.sql.startsWith("INSERT INTO weather_record_values")) { const [metric, numeric_value, observed_at, local_date, updated_at] = item.values; this.records.set(metric, { metric, numeric_value, observed_at, local_date, updated_at }); } else if (item.sql.startsWith("UPDATE weather_rollup_state")) { const [first, last, count, cursor, reconciled, updated] = item.values; Object.assign(this.state, { first_observed_at: first, last_observed_at: last, observation_count: count, rollup_cursor_observed_at: cursor, dirty_from_local_date: null, status: "backfilling", last_reconciled_at: reconciled, updated_at: updated }); } else throw new Error(`BATCH no simulado: ${item.sql}`); } return []; }
}

assert.equal(localDate("2026-01-01T02:59:59.000Z"), "2025-12-31");
assert.equal(localDate("2026-01-01T03:00:00.000Z"), "2026-01-01");
assert.equal(localDate("2026-02-01T02:59:59.000Z"), "2026-01-31");
assert.equal(localDate("2027-01-01T03:00:00.000Z"), "2027-01-01");
const direct = aggregateRows(FIXTURES); const jan = direct.get("2026-01-01");
assert.ok(Math.abs(jan.precipitation_total - 3.9) < 1e-9, "primer valor, incrementos y dos reinicios");
assert.equal(jan.precipitation_sample_count, 6); assert.equal(jan.last_precip_total, .4); assert.equal(jan.temperature_max, 20); assert.equal(jan.temperature_max_at, "2026-01-01T03:00:00.000Z", "empate conserva el primero");
const interrupted = new FakeD1(FIXTURES); const stamp = new Date("2027-02-01T00:00:00.000Z"); const first = await backfillBatch(interrupted, { batchSize: 3, now: stamp }); assert.equal(first.processed, 3); assert.equal(interrupted.state.rollup_cursor_observed_at, FIXTURES[2].observed_at);
const resumed = await runBackfill(interrupted, { batchSize: 3, now: stamp }); assert.equal(resumed.total, FIXTURES.length - 3); const resumedReport = await validateDatabaseEquivalence(interrupted); assert.equal(resumedReport.ok, true); assert.equal((await finalizeBackfill(interrupted, { now: stamp })).finalized, true); assert.equal(interrupted.state.status, "ready");
const uninterrupted = new FakeD1(FIXTURES); await runBackfill(uninterrupted, { batchSize: 3, now: stamp }); await finalizeBackfill(uninterrupted, { now: stamp }); assert.deepEqual([...interrupted.days.values()], [...uninterrupted.days.values()]); assert.deepEqual([...interrupted.records.values()], [...uninterrupted.records.values()]); assert.deepEqual(interrupted.state, uninterrupted.state);
const before = structuredClone({ state: interrupted.state, days: [...interrupted.days.values()], records: [...interrupted.records.values()] }); const idempotent = await runBackfill(interrupted, { batchSize: 3, now: stamp }); assert.equal(idempotent.total, 0); assert.deepEqual({ state: interrupted.state, days: [...interrupted.days.values()], records: [...interrupted.records.values()] }, before);
const broken = validateEquivalence(FIXTURES, { ...interrupted.state, observation_count: 999 }, [...interrupted.days.values()], [...interrupted.records.values()]); assert.equal(broken.ok, false); assert.ok(broken.mismatches.includes("metadata.observation_count")); const periods = validatePeriodStatistics(FIXTURES, [...interrupted.days.values()]); assert.equal(periods.ok, true, JSON.stringify(periods));
console.log("weather rollups tests: OK (ART boundaries, precipitation resets, ties, resume, idempotence and equivalence)");