const INDEX_URL = "https://ws2.smn.gob.ar/rss";
const FALLBACK_FEED = "https://ssl.smn.gob.ar/feeds/CAP/rss_alertaCAP_nuevo_2026.xml";
const SMN_HOSTS = new Set(["ws2.smn.gob.ar", "ssl.smn.gob.ar"]);
const ITUZAINGO = { lat: -34.655, lon: -58.667 };
const TTL = 300;
export const CAP_BATCH_SIZE = 8;
export const CAP_CONCURRENCY = 3;
export const CAP_TIMEOUT_MS = 8000;
const DISCOVERY_INTERVAL_MS = 6 * 60 * 60 * 1000;
const LEASE_MS = 9 * 60 * 1000;
const iso = (ms = Date.now()) => new Date(ms).toISOString();
function safeUrl(raw) { try { const url = new URL(raw); return url.protocol === "https:" && SMN_HOSTS.has(url.hostname) ? url : null; } catch { return null; } }
function xml(body) { if (/<!DOCTYPE|<!ENTITY/i.test(body)) throw new Error("XML inseguro"); return body; }
function values(source, tag) { const result = []; let start = 0; const open = `<${tag}>`, close = `</${tag}>`; while ((start = source.indexOf(open, start)) >= 0) { const end = source.indexOf(close, start + open.length); if (end < 0) break; result.push(source.slice(start + open.length, end).replace(/&#x([0-9a-f]+);|&#(\d+);|&amp;|&lt;|&gt;/gi, (_, hex, dec) => hex ? String.fromCodePoint(parseInt(hex, 16)) : dec ? String.fromCodePoint(Number(dec)) : ({ "&amp;": "&", "&lt;": "<", "&gt;": ">" }[_] || _)).trim()); start = end + close.length; } return result; }
function blocks(source, tag) { const result = []; let start = 0; const open = `<${tag}`, close = `</${tag}>`; while ((start = source.indexOf(open, start)) >= 0) { const begin = source.indexOf(">", start), end = source.indexOf(close, begin); if (begin < 0 || end < 0) break; result.push(source.slice(begin + 1, end)); start = end + close.length; } return result; }
function pointOnEdge(a, b) { const cross = (ITUZAINGO.lon - a.lon) * (b.lat - a.lat) - (ITUZAINGO.lat - a.lat) * (b.lon - a.lon); return Math.abs(cross) < 1e-9 && ITUZAINGO.lon >= Math.min(a.lon, b.lon) && ITUZAINGO.lon <= Math.max(a.lon, b.lon) && ITUZAINGO.lat >= Math.min(a.lat, b.lat) && ITUZAINGO.lat <= Math.max(a.lat, b.lat); }
export function pointInPolygon(raw) { const p = raw.trim().split(/\s+/).map((pair) => pair.split(",").map(Number)).filter(([lat, lon]) => Number.isFinite(lat) && Number.isFinite(lon)).map(([lat, lon]) => ({ lat, lon })); if (p.length < 3) return false; let inside = false; for (let i = 0, j = p.length - 1; i < p.length; j = i++) { if (pointOnEdge(p[j], p[i])) return true; if ((p[i].lat > ITUZAINGO.lat) !== (p[j].lat > ITUZAINGO.lat) && ITUZAINGO.lon < (p[j].lon - p[i].lon) * (ITUZAINGO.lat - p[i].lat) / (p[j].lat - p[i].lat) + p[i].lon) inside = !inside; } return inside; }
function active(info, now) { const expires = values(info, "expires")[0], onset = values(info, "onset")[0] || values(info, "effective")[0] || null; return expires && Date.parse(expires) > now && (!onset || Number.isFinite(Date.parse(onset))); }
function references(root) { return [...new Set((values(root, "references")[0] || "").match(/urn:oid:[^,\s]+/g) || [])]; }
/** Matches an exact CAP identifier or an SMN area-variant with its final dot component. */
export function referenceMatchesCapIdentifier(referencedIdentifier, capIdentifier) {
  return typeof referencedIdentifier === "string" && typeof capIdentifier === "string" && (capIdentifier === referencedIdentifier || capIdentifier.startsWith(`${referencedIdentifier}.`));
}
async function fetchText(url, timeout = CAP_TIMEOUT_MS, fetcher = fetch) { const response = await fetcher(url, { signal: AbortSignal.timeout(timeout), headers: { Accept: "application/xml,text/xml,application/rss+xml,*/*", "User-Agent": "MeteoItuzaingo-SMNAlerts/1.13.2" } }); if (!response.ok) throw new Error(`SMN ${response.status}`); return xml(await response.text()); }
async function discoverFeed(fetcher = fetch) { const response = await fetcher(INDEX_URL, { signal: AbortSignal.timeout(CAP_TIMEOUT_MS), headers: { Accept: "text/html,*/*", "User-Agent": "MeteoItuzaingo-SMNAlerts/1.13.2" } }); if (!response.ok) throw new Error(`SMN ${response.status}`); const candidate = ((await response.text()).match(/https:\/\/ssl\.smn\.gob\.ar\/feeds\/CAP\/rss_alertaCAP_nuevo_[^"'<\s]+\.xml/) || [])[0]; if (!safeUrl(candidate)) throw new Error("Feed SMN no encontrado"); return candidate; }
export async function mapWithConcurrency(items, concurrency, handler) { const result = new Array(items.length); let cursor = 0; await Promise.all(Array.from({ length: Math.min(concurrency, items.length) }, async () => { while (cursor < items.length) { const index = cursor++; result[index] = await handler(items[index], index); } })); return result; }
export function rssIdentities(rss) { return [...new Set(blocks(rss, "item").map((item) => safeUrl(values(item, "guid")[0] || values(item, "link")[0])).filter(Boolean).map(String))]; }
export function normalizeCap(capUrl, root, now = Date.now()) { const msgType = values(root, "msgType")[0] || "Alert", id = values(root, "identifier")[0] || null; const infos = msgType === "Cancel" ? [] : blocks(root, "info").filter((info) => active(info, now)).map((info) => { const areas = blocks(info, "area"), geometry = areas.flatMap((area) => values(area, "polygon")); if (!geometry.some(pointInPolygon)) return null; return { id, source: "SMN", type: "alert", event: values(info, "event")[0] || "Alerta meteorológica", headline: values(info, "headline")[0] || null, description: values(info, "description")[0] || null, instructions: values(info, "instruction")[0] || null, areaDescription: areas.map((area) => values(area, "areaDesc")[0]).filter(Boolean).join(" · ") || null, effective: values(info, "effective")[0] || null, onset: values(info, "onset")[0] || null, expires: values(info, "expires")[0], sent: values(root, "sent")[0] || null, msgType, references: values(root, "references")[0] || null, officialUrl: "https://ws2.smn.gob.ar/alertas", capUrl }; }).filter(Boolean); const first = blocks(root, "info")[0] || ""; return { capUrl, identifier: id, msgType, refs: references(root), sentAt: values(root, "sent")[0] || null, onsetAt: values(first, "onset")[0] || values(first, "effective")[0] || null, expiresAt: values(first, "expires")[0] || null, applicable: infos.length > 0, payload: infos }; }
function chunks(items, size) { return Array.from({ length: Math.ceil(items.length / size) }, (_, index) => items.slice(index * size, index * size + size)); }
async function saveState(db, fields) { const keys = Object.keys(fields); await db.prepare(`UPDATE smn_ingestion_state SET ${keys.map((key) => `${key} = ?`).join(", ")} WHERE id = 1`).bind(...keys.map((key) => fields[key])).run(); }
async function state(db) { return db.prepare("SELECT * FROM smn_ingestion_state WHERE id = 1").first(); }
async function acquireLease(db, now) { await db.prepare("INSERT OR IGNORE INTO smn_ingestion_state (id, scan_generation, bootstrap_completed, updated_at) VALUES (1, 0, 0, ?)").bind(iso(now)).run(); const result = await db.prepare("UPDATE smn_ingestion_state SET lease_until = ?, updated_at = ? WHERE id = 1 AND (lease_until IS NULL OR lease_until <= ?)").bind(iso(now + LEASE_MS), iso(now), iso(now)).run(); return result.meta.changes === 1; }
async function registerItems(db, urls, priority, now) { for (const group of chunks(urls, 25)) { const placeholders = group.map(() => "(?, ?, 'pending', ?, ?)").join(","); await db.prepare(`INSERT OR IGNORE INTO smn_cap_items (cap_url, first_seen_at, processing_status, priority, updated_at) VALUES ${placeholders}`).bind(...group.flatMap((url) => [url, now, priority ? 1 : 0, now])).run(); } }
function shouldDiscover(current, now) { return !current?.feed_url || !current.discovery_checked_at || Date.parse(current.discovery_checked_at) + DISCOVERY_INTERVAL_MS <= now || !current.feed_url.includes(`_${new Date(now).getUTCFullYear()}.xml`); }
function nextRetry(attempts, now) { return iso(now + Math.min(60, 5 * 2 ** Math.min(attempts, 4)) * 60000); }
async function persistResult(db, result, now) { if (!result.ok) return db.prepare("UPDATE smn_cap_items SET processing_status = 'retry', attempts = attempts + 1, next_retry_at = ?, last_error = ?, updated_at = ? WHERE cap_url = ?").bind(nextRetry(result.item.attempts || 0, now), result.error, iso(now), result.item.cap_url).run(); const cap = result.cap; await db.prepare("UPDATE smn_cap_items SET cap_identifier=?, msg_type=?, references_text=?, sent_at=?, onset_at=?, expires_at=?, applicable_to_ituzaingo=?, public_payload_json=?, processing_status='success', attempts=attempts+1, next_retry_at=NULL, last_error=NULL, processed_at=?, updated_at=? WHERE cap_url=?").bind(cap.identifier, cap.msgType, cap.refs.join(","), cap.sentAt, cap.onsetAt, cap.expiresAt, cap.applicable ? 1 : 0, JSON.stringify(cap.payload), iso(now), iso(now), cap.capUrl).run(); if (cap.identifier && ["Update", "Cancel"].includes(cap.msgType)) for (const referenced of cap.refs) await db.prepare("INSERT OR IGNORE INTO smn_cap_references (source_identifier, referenced_identifier, relation_type, created_at) VALUES (?, ?, ?, ?)").bind(cap.identifier, referenced, cap.msgType.toUpperCase(), iso(now)).run(); }
export async function ingestSmnAlerts(env, { now = Date.now(), fetcher = fetch } = {}) { const db = env.HISTORY_DB; if (!(await acquireLease(db, now))) return { status: "locked" }; const started = Date.now(); try { let current = await state(db), feedUrl = current.feed_url; if (shouldDiscover(current, now)) { try { feedUrl = await discoverFeed(fetcher); await saveState(db, { feed_url: feedUrl, discovery_checked_at: iso(now), last_error_code: null, updated_at: iso(now) }); } catch (error) { if (!feedUrl) feedUrl = FALLBACK_FEED; else console.warn("[smn] discovery failed; using persisted feed", error?.message || String(error)); } } const rss = await fetchText(safeUrl(feedUrl), CAP_TIMEOUT_MS, fetcher), urls = rssIdentities(rss); if (!urls.length) throw new Error("RSS SMN sin items válidos"); current = await state(db); await registerItems(db, urls, Boolean(current.bootstrap_completed), iso(now)); await saveState(db, { feed_fetched_at: iso(now), last_success_at: iso(now), scan_generation: Number(current.scan_generation || 0) + 1, last_error_code: null, updated_at: iso(now) }); const due = await db.prepare("SELECT cap_url, attempts FROM smn_cap_items WHERE processing_status IN ('pending', 'retry') AND (next_retry_at IS NULL OR next_retry_at <= ?) ORDER BY priority DESC, first_seen_at ASC, cap_url ASC LIMIT ?").bind(iso(now), CAP_BATCH_SIZE).all(); const results = await mapWithConcurrency(due.results, CAP_CONCURRENCY, async (item) => { try { return { ok: true, item, cap: normalizeCap(item.cap_url, await fetchText(safeUrl(item.cap_url), CAP_TIMEOUT_MS, fetcher), now) }; } catch (error) { console.warn("[smn] CAP failed", item.cap_url, error?.message || String(error)); return { ok: false, item, error: String(error?.message || error) }; } }); for (const result of results) await persistResult(db, result, now); const pending = await db.prepare("SELECT COUNT(*) AS count FROM smn_cap_items WHERE processing_status IN ('pending', 'retry')").first(); if (!pending?.count) await saveState(db, { bootstrap_completed: 1, last_complete_scan_at: iso(now), updated_at: iso(now) }); console.log(JSON.stringify({ event: "smn_ingestion", discovered: urls.length, processed: results.filter((result) => result.ok).length, failed: results.filter((result) => !result.ok).length, pending: pending?.count || 0, applicable: results.filter((result) => result.ok && result.cap.applicable).length, durationMs: Date.now() - started })); return { status: "ok", discovered: urls.length, processed: results.length, failed: results.filter((result) => !result.ok).length, pending: pending?.count || 0 }; } catch (error) { await saveState(db, { last_error_code: String(error?.message || error).slice(0, 180), updated_at: iso(now) }); console.error("[smn] RSS failed", error?.message || String(error)); return { status: "rss_failed" }; } finally { await db.prepare("UPDATE smn_ingestion_state SET lease_until = NULL, updated_at = ? WHERE id = 1").bind(iso()).run(); } }
export async function alertsResponse(database) { const key = new Request("https://meteoituzaingo.internal/api/alerts"), hit = await caches.default.match(key); if (hit) return hit; const now = iso(); const [items, ingestion] = await Promise.all([database.prepare("SELECT public_payload_json FROM smn_cap_items item WHERE item.processing_status='success' AND item.applicable_to_ituzaingo=1 AND item.msg_type!='Cancel' AND datetime(item.expires_at) > datetime(?) AND NOT EXISTS (SELECT 1 FROM smn_cap_references relation JOIN smn_cap_items successor ON successor.cap_identifier=relation.source_identifier AND successor.processing_status='success' WHERE (relation.referenced_identifier=item.cap_identifier OR item.cap_identifier LIKE relation.referenced_identifier || '.%') AND relation.relation_type IN ('UPDATE','CANCEL')) ORDER BY datetime(item.expires_at) ASC").bind(now).all(), database.prepare("SELECT last_success_at, feed_url FROM smn_ingestion_state WHERE id=1").first()]); const alerts = items.results.flatMap((item) => { try { return JSON.parse(item.public_payload_json || "[]"); } catch { return []; } }); const body = { ok: true, updatedAt: ingestion?.last_success_at || null, location: "Ituzaingó, Buenos Aires", alerts, source: { name: "Servicio Meteorológico Nacional (SMN)", url: "https://ws2.smn.gob.ar/alertas" }, feed: ingestion?.feed_url || null }; const response = new Response(JSON.stringify(body), { headers: { "Content-Type": "application/json; charset=utf-8", "Cache-Control": `public, max-age=${TTL}` } }); await caches.default.put(key, response.clone()); return response; }
