const INDEX_URL = "https://ws2.smn.gob.ar/rss";
const FALLBACK_FEED = "https://ssl.smn.gob.ar/feeds/CAP/rss_alertaCAP_nuevo_2026.xml";
const SMN_HOSTS = new Set(["ws2.smn.gob.ar", "ssl.smn.gob.ar"]);
const ITUZAINGO = { lat: -34.655, lon: -58.667 };
const TTL = 300;
const text = new TextDecoder();
function safeUrl(raw) { try { const url = new URL(raw); return url.protocol === "https:" && SMN_HOSTS.has(url.hostname) ? url : null; } catch { return null; } }
function xml(response) { const body = response; if (/<!DOCTYPE|<!ENTITY/i.test(body)) throw new Error("XML inseguro"); return body; }
function values(source, tag) { const result = []; let start = 0; const open = `<${tag}>`, close = `</${tag}>`; while ((start = source.indexOf(open, start)) >= 0) { const end = source.indexOf(close, start + open.length); if (end < 0) break; result.push(source.slice(start + open.length, end).replace(/&#x([0-9a-f]+);|&#(\d+);|&amp;|&lt;|&gt;/gi, (_, hex, dec) => hex ? String.fromCodePoint(parseInt(hex, 16)) : dec ? String.fromCodePoint(Number(dec)) : ({ "&amp;": "&", "&lt;": "<", "&gt;": ">" }[_] || _)).trim()); start = end + close.length; } return result; }
function blocks(source, tag) { const result = []; let start = 0; const open = `<${tag}`, close = `</${tag}>`; while ((start = source.indexOf(open, start)) >= 0) { const begin = source.indexOf(">", start); const end = source.indexOf(close, begin); if (begin < 0 || end < 0) break; result.push(source.slice(begin + 1, end)); start = end + close.length; } return result; }
function pointOnEdge(a, b) { const cross = (ITUZAINGO.lon - a.lon) * (b.lat - a.lat) - (ITUZAINGO.lat - a.lat) * (b.lon - a.lon); return Math.abs(cross) < 1e-9 && ITUZAINGO.lon >= Math.min(a.lon, b.lon) && ITUZAINGO.lon <= Math.max(a.lon, b.lon) && ITUZAINGO.lat >= Math.min(a.lat, b.lat) && ITUZAINGO.lat <= Math.max(a.lat, b.lat); }
export function pointInPolygon(raw) { const p = raw.trim().split(/\s+/).map((pair) => pair.split(",").map(Number)).filter(([lat, lon]) => Number.isFinite(lat) && Number.isFinite(lon)).map(([lat, lon]) => ({ lat, lon })); if (p.length < 3) return false; let inside = false; for (let i = 0, j = p.length - 1; i < p.length; j = i++) { if (pointOnEdge(p[j], p[i])) return true; if ((p[i].lat > ITUZAINGO.lat) !== (p[j].lat > ITUZAINGO.lat) && ITUZAINGO.lon < (p[j].lon - p[i].lon) * (ITUZAINGO.lat - p[i].lat) / (p[j].lat - p[i].lat) + p[i].lon) inside = !inside; } return inside; }
function active(info, now) { const expires = values(info, "expires")[0]; const onset = values(info, "onset")[0] || values(info, "effective")[0] || null; return expires && Date.parse(expires) > now && (!onset || Number.isFinite(Date.parse(onset))); }
async function fetchText(url, timeout = 8000) { console.log(`[alerts] fetch:start ${url}`); const signal = AbortSignal.timeout(timeout); const response = await fetch(url, { signal, headers: { Accept: "application/xml,text/xml,application/rss+xml,*/*", "User-Agent": "MeteoItuzaingo-SMNAlerts/1.9" } }); console.log(`[alerts] fetch:status=${response.status} url=${response.url}`); if (!response.ok) throw new Error(`SMN ${response.status}`); const body = await response.text(); console.log(`[alerts] fetch:bytes=${body.length}`); return xml(body); }
async function discoverFeed() { try { const response = await fetch(INDEX_URL, { headers: { Accept: "text/html,*/*", "User-Agent": "MeteoItuzaingo-SMNAlerts/1.9" }, signal: AbortSignal.timeout(8000) }); if (!response.ok) throw new Error(`SMN ${response.status}`); const html = await response.text(); const candidate = (html.match(/https:\/\/ssl\.smn\.gob\.ar\/feeds\/CAP\/rss_alertaCAP_nuevo_[^"'<\s]+\.xml/) || [])[0]; if (safeUrl(candidate)?.pathname.startsWith("/feeds/CAP/rss_alertaCAP_nuevo_")) return candidate; } catch (error) { console.warn("[alerts] discovery failed", error?.message || String(error)); } return FALLBACK_FEED; }
export async function getSmnAlerts() {
  console.log("[alerts] start"); const feedLink = await discoverFeed(); console.log(`[alerts] discovery=${feedLink || "none"}`);
  const feed = safeUrl(feedLink); if (!feed) throw new Error("Feed SMN no encontrado"); const rss = await fetchText(feed); const items = blocks(rss, "item").map((item) => safeUrl(values(item, "link")[0] || values(item, "guid")[0])).filter(Boolean).slice(0, 40);
  const now = Date.now(); const caps = await Promise.all(items.map(async (url) => { try { return { url, source: await fetchText(url) }; } catch { return null; } }));
  const alerts = [];
  for (const cap of caps.filter(Boolean)) { const root = cap.source; const msgType = values(root, "msgType")[0] || "Alert"; if (msgType === "Cancel") continue; const id = values(root, "identifier")[0]; for (const info of blocks(root, "info")) { if (!active(info, now)) continue; const areas = blocks(info, "area"); const geometry = areas.flatMap((area) => values(area, "polygon")); if (!geometry.some(pointInPolygon)) continue; alerts.push({ id, source: "SMN", type: "alert", event: values(info, "event")[0] || "Alerta meteorológica", headline: values(info, "headline")[0] || null, description: values(info, "description")[0] || null, instructions: values(info, "instruction")[0] || null, areaDescription: areas.map((area) => values(area, "areaDesc")[0]).filter(Boolean).join(" · ") || null, effective: values(info, "effective")[0] || null, onset: values(info, "onset")[0] || null, expires: values(info, "expires")[0], sent: values(root, "sent")[0] || null, msgType, references: values(root, "references")[0] || null, officialUrl: "https://ws2.smn.gob.ar/alertas" }); }
  }
  return { ok: true, updatedAt: new Date().toISOString(), location: "Ituzaingó, Buenos Aires", alerts, source: { name: "Servicio Meteorológico Nacional (SMN)", url: "https://ws2.smn.gob.ar/alertas" }, feed: feed.toString() };
}
export async function alertsResponse() { const key = new Request("https://meteoituzaingo.internal/api/alerts"); const hit = await caches.default.match(key); if (hit) return hit; const body = await getSmnAlerts(); const response = new Response(JSON.stringify(body), { headers: { "Content-Type": "application/json; charset=utf-8", "Cache-Control": `public, max-age=${TTL}` } }); await caches.default.put(key, response.clone()); return response; }
async function probe(url) { const started = Date.now(); try { const body = await fetchText(url); return { ok: true, status: 200, host: new URL(url).host, finalUrl: url, bodyLength: body.length, durationMs: Date.now() - started, body }; } catch (error) { return { ok: false, host: new URL(url).host, durationMs: Date.now() - started, error: { name: error?.name || "Error", message: String(error?.message || error) } }; } }
