export const ARGENTINA_TIME_ZONE = "America/Argentina/Buenos_Aires";
export const ROLLUP_BATCH_SIZE = 250;
const LIMITS = { temperature: [-90, 70], humidity: [0, 100], pressure: [800, 1100], windSpeed: [0, 300], windGust: [0, 400], precipTotal: [0, 2000] };
const RECORDS = [["temperature_max", "temperature", "max"], ["temperature_min", "temperature", "min"], ["wind_gust_max", "wind_gust", "max"], ["pressure_max", "pressure", "max"], ["pressure_min", "pressure", "min"], ["humidity_max", "humidity", "max"], ["humidity_min", "humidity", "min"]];
const iso = (now = new Date()) => new Date(now).toISOString();
const finite = (value) => Number.isFinite(value);
const valid = (value, key) => finite(value) && value >= LIMITS[key][0] && value <= LIMITS[key][1];
export function localDate(timestamp) { const parts = Object.fromEntries(new Intl.DateTimeFormat("en-GB", { timeZone: ARGENTINA_TIME_ZONE, year: "numeric", month: "2-digit", day: "2-digit" }).formatToParts(new Date(timestamp)).filter((part) => part.type !== "literal").map((part) => [part.type, part.value])); return `${parts.year}-${parts.month}-${parts.day}`; }
function blankDay(date) { return { local_date: date, first_observed_at: null, last_observed_at: null, observation_count: 0, temperature_count: 0, temperature_sum: 0, temperature_min: null, temperature_min_at: null, temperature_max: null, temperature_max_at: null, humidity_count: 0, humidity_sum: 0, humidity_min: null, humidity_min_at: null, humidity_max: null, humidity_max_at: null, pressure_count: 0, pressure_sum: 0, pressure_min: null, pressure_min_at: null, pressure_max: null, pressure_max_at: null, wind_count: 0, wind_sum: 0, wind_max: null, wind_max_at: null, gust_max: null, gust_max_at: null, precipitation_total: null, precipitation_sample_count: 0, last_precip_total: null, last_precip_observed_at: null }; }
function normalizedDay(row) { return { ...blankDay(row?.local_date), ...(row || {}) }; }
function better(value, at, current, currentAt, direction) { return current === null || current === undefined || (direction === "max" ? value > current : value < current) || (value === current && at < currentAt); }
function addMetric(day, row, name, column, limitKey) { const value = row[column]; if (!valid(value, limitKey)) return; day[`${name}_count`] += 1; day[`${name}_sum`] += value; for (const direction of ["min", "max"]) if (better(value, row.observed_at, day[`${name}_${direction}`], day[`${name}_${direction}_at`], direction)) { day[`${name}_${direction}`] = value; day[`${name}_${direction}_at`] = row.observed_at; } }
function addMax(day, row, name, column, limitKey) { const value = row[column]; if (valid(value, limitKey) && better(value, row.observed_at, day[`${name}_max`], day[`${name}_max_at`], "max")) { day[`${name}_max`] = value; day[`${name}_max_at`] = row.observed_at; } }
export function applyObservation(dayInput, row) { const day = normalizedDay(dayInput); if (!day.first_observed_at || row.observed_at < day.first_observed_at) day.first_observed_at = row.observed_at; if (!day.last_observed_at || row.observed_at > day.last_observed_at) day.last_observed_at = row.observed_at; day.observation_count += 1; addMetric(day, row, "temperature", "temperature", "temperature"); addMetric(day, row, "humidity", "humidity", "humidity"); addMetric(day, row, "pressure", "pressure", "pressure"); addMetric(day, row, "wind", "wind_speed", "windSpeed"); addMax(day, row, "gust", "wind_gust", "windGust"); const value = row.precip_total; if (valid(value, "precipTotal")) { day.precipitation_total = (day.precipitation_total ?? 0) + (day.precipitation_sample_count === 0 ? value : value >= day.last_precip_total ? value - day.last_precip_total : value); day.precipitation_sample_count += 1; day.last_precip_total = value; day.last_precip_observed_at = row.observed_at; } return day; }
export function aggregateRows(rows, existing = new Map()) { const days = new Map([...existing.entries()].filter(([, row]) => row).map(([date, row]) => [date, normalizedDay(row)])); for (const row of [...rows].sort((a, b) => a.observed_at.localeCompare(b.observed_at))) { const date = localDate(row.observed_at); days.set(date, applyObservation(days.get(date) || blankDay(date), row)); } return days; }
function recordBetter(candidate, current, direction, field = "observed_at") { if (!current) return true; if (candidate.numeric_value === null || candidate.numeric_value === undefined) return false; return direction === "max" ? candidate.numeric_value > current.numeric_value || candidate.numeric_value === current.numeric_value && candidate[field] < current[field] : candidate.numeric_value < current.numeric_value || candidate.numeric_value === current.numeric_value && candidate[field] < current[field]; }
export function materializeRecords(rows, days, existing = new Map()) { const output = new Map(existing); for (const [metric, column, direction] of RECORDS) for (const row of rows) if (finite(row[column])) { const candidate = { metric, numeric_value: row[column], observed_at: row.observed_at, local_date: null }; const current = output.get(metric); if (recordBetter(candidate, current, direction)) output.set(metric, candidate); } for (const day of days.values()) if (finite(day.precipitation_total)) { const candidate = { metric: "precipitation_daily_max", numeric_value: day.precipitation_total, observed_at: null, local_date: day.local_date }; const current = output.get(candidate.metric); if (recordBetter(candidate, current, "max", "local_date")) output.set(candidate.metric, candidate); } return output; }
const dayColumns = ["local_date", "first_observed_at", "last_observed_at", "observation_count", "temperature_count", "temperature_sum", "temperature_min", "temperature_min_at", "temperature_max", "temperature_max_at", "humidity_count", "humidity_sum", "humidity_min", "humidity_min_at", "humidity_max", "humidity_max_at", "pressure_count", "pressure_sum", "pressure_min", "pressure_min_at", "pressure_max", "pressure_max_at", "wind_count", "wind_sum", "wind_max", "wind_max_at", "gust_max", "gust_max_at", "precipitation_total", "precipitation_sample_count", "last_precip_total", "last_precip_observed_at"];
function upsertDay(database, day, now) { const columns = [...dayColumns, "updated_at"]; const update = columns.filter((column) => column !== "local_date").map((column) => `${column}=excluded.${column}`).join(", "); return database.prepare(`INSERT INTO weather_daily_aggregates (${columns.join(", ")}) VALUES (${columns.map(() => "?").join(", ")}) ON CONFLICT(local_date) DO UPDATE SET ${update}`).bind(...columns.map((column) => column === "updated_at" ? now : day[column])); }
function upsertRecord(database, record, now) { return database.prepare("INSERT INTO weather_record_values (metric, numeric_value, observed_at, local_date, updated_at) VALUES (?, ?, ?, ?, ?) ON CONFLICT(metric) DO UPDATE SET numeric_value=excluded.numeric_value, observed_at=excluded.observed_at, local_date=excluded.local_date, updated_at=excluded.updated_at").bind(record.metric, record.numeric_value, record.observed_at, record.local_date, now); }
function updateState(database, state, rows, now) { const first = state.first_observed_at && state.first_observed_at < rows[0].observed_at ? state.first_observed_at : rows[0].observed_at; const last = state.last_observed_at && state.last_observed_at > rows.at(-1).observed_at ? state.last_observed_at : rows.at(-1).observed_at; return database.prepare("UPDATE weather_rollup_state SET first_observed_at=?, last_observed_at=?, observation_count=?, rollup_cursor_observed_at=?, dirty_from_local_date=NULL, status='backfilling', last_reconciled_at=?, updated_at=? WHERE id=1").bind(first, last, Number(state.observation_count || 0) + rows.length, rows.at(-1).observed_at, now, now); }
export async function backfillBatch(database, { batchSize = ROLLUP_BATCH_SIZE, now = new Date() } = {}) { const state = await database.prepare("SELECT * FROM weather_rollup_state WHERE id=1").first(); if (!state) throw new Error("ROLLUP_STATE_MISSING"); const result = await database.prepare("SELECT * FROM weather_observations WHERE (? IS NULL OR observed_at > ?) ORDER BY observed_at ASC LIMIT ?").bind(state.rollup_cursor_observed_at, state.rollup_cursor_observed_at, batchSize).all(); const rows = result.results || []; if (!rows.length) return { processed: 0, complete: true, cursor: state.rollup_cursor_observed_at, status: state.status }; const dates = [...new Set(rows.map((row) => localDate(row.observed_at)))]; const currentDays = new Map(await Promise.all(dates.map(async (date) => [date, await database.prepare("SELECT * FROM weather_daily_aggregates WHERE local_date=?").bind(date).first()]))); const days = aggregateRows(rows, currentDays); const existingRecords = new Map((await database.prepare("SELECT * FROM weather_record_values").all()).results.map((row) => [row.metric, row])); const records = materializeRecords(rows, days, existingRecords); const stamp = iso(now); await database.batch([...days.values()].map((day) => upsertDay(database, day, stamp)).concat([...records.values()].map((record) => upsertRecord(database, record, stamp)), updateState(database, state, rows, stamp))); return { processed: rows.length, complete: rows.length < batchSize, cursor: rows.at(-1).observed_at, status: "backfilling" }; }
export async function runBackfill(database, options = {}) { let total = 0; for (;;) { const batch = await backfillBatch(database, options); total += batch.processed; if (batch.complete) return { ...batch, total }; } }
export function snapshotFromRaw(rows) { const days = aggregateRows(rows); return { metadata: rows.length ? { first_observed_at: rows[0].observed_at, last_observed_at: rows.at(-1).observed_at, observation_count: rows.length } : { first_observed_at: null, last_observed_at: null, observation_count: 0 }, days, records: materializeRecords(rows, days) }; }
function close(left, right, tolerance = 1e-9) { return left === right || finite(left) && finite(right) && Math.abs(left - right) <= tolerance; }
export function validateEquivalence(rows, state, dailyRows, recordRows, tolerance = 1e-9) { const expected = snapshotFromRaw([...rows].sort((a, b) => a.observed_at.localeCompare(b.observed_at))); const mismatches = []; for (const key of ["first_observed_at", "last_observed_at", "observation_count"]) if (expected.metadata[key] !== state[key]) mismatches.push(`metadata.${key}`); for (const [date, day] of expected.days) { const actual = dailyRows.find((item) => item.local_date === date); for (const key of dayColumns) if (!actual || !close(day[key], actual[key])) mismatches.push(`daily.${date}.${key}`); } for (const [metric, record] of expected.records) { const actual = recordRows.find((item) => item.metric === metric); for (const key of ["numeric_value", "observed_at", "local_date"]) if (!actual || !close(record[key], actual[key])) mismatches.push(`record.${metric}.${key}`); } return { ok: mismatches.length === 0, exact: mismatches.length === 0, tolerance, mismatches, expected }; }
export async function validateDatabaseEquivalence(database, tolerance = 1e-9) { const [raw, state, daily, records] = await Promise.all([database.prepare("SELECT * FROM weather_observations ORDER BY observed_at ASC").all(), database.prepare("SELECT * FROM weather_rollup_state WHERE id=1").first(), database.prepare("SELECT * FROM weather_daily_aggregates ORDER BY local_date ASC").all(), database.prepare("SELECT * FROM weather_record_values ORDER BY metric ASC").all()]); return validateEquivalence(raw.results || [], state || {}, daily.results || [], records.results || [], tolerance); }

export async function finalizeBackfill(database, { now = new Date(), tolerance = 1e-9 } = {}) { const report = await validateDatabaseEquivalence(database, tolerance); if (!report.ok) return { ...report, finalized: false }; const stamp = iso(now); await database.prepare("UPDATE weather_rollup_state SET status='ready', last_reconciled_at=?, updated_at=? WHERE id=1").bind(stamp, stamp).run(); return { ...report, finalized: true }; }
function finiteMin(values) { const validValues = values.filter(finite); return validValues.length ? Math.min(...validValues) : null; }
function finiteMax(values) { const validValues = values.filter(finite); return validValues.length ? Math.max(...validValues) : null; }
export function statisticsFromDaily(dailyRows, predicate = () => true) { const days = dailyRows.filter(predicate); const summarize = (name) => { const count = days.reduce((total, day) => total + Number(day[`${name}_count`] || 0), 0); const sum = days.reduce((total, day) => total + Number(day[`${name}_sum`] || 0), 0); return { count, average: count ? sum / count : null, min: finiteMin(days.map((day) => day[`${name}_min`])), max: finiteMax(days.map((day) => day[`${name}_max`])) }; }; return { observations: days.reduce((total, day) => total + Number(day.observation_count || 0), 0), temperature: summarize("temperature"), humidity: summarize("humidity"), pressure: summarize("pressure"), wind: summarize("wind"), gustMax: finiteMax(days.map((day) => day.gust_max)), precipitation: days.reduce((total, day) => total + (finite(day.precipitation_total) ? day.precipitation_total : 0), 0) }; }
export function statisticsFromRaw(rows, predicate = () => true) { return statisticsFromDaily([...aggregateRows(rows).values()], predicate); }
export function validatePeriodStatistics(rows, dailyRows, predicates = { month: (day) => day.local_date.startsWith("2026-01"), year: (day) => day.local_date.startsWith("2026"), all: () => true }, tolerance = 1e-9) { const mismatches = []; for (const [period, predicate] of Object.entries(predicates)) { const expected = statisticsFromRaw(rows, predicate); const actual = statisticsFromDaily(dailyRows, predicate); for (const key of ["observations", "gustMax", "precipitation"]) if (!close(expected[key], actual[key], tolerance)) mismatches.push(`${period}.${key}`); for (const metric of ["temperature", "humidity", "pressure"]) for (const key of ["count", "average", "min", "max"]) if (!close(expected[metric][key], actual[metric][key], tolerance)) mismatches.push(`${period}.${metric}.${key}`); for (const key of ["count", "average", "max"]) if (!close(expected.wind[key], actual.wind[key], tolerance)) mismatches.push(`${period}.wind.${key}`); } return { ok: mismatches.length === 0, tolerance, mismatches }; }